import logo from '../assets/Caleb.png'
import manComputer from '../assets/man-computer.png'
import manComputer2 from '../assets/man-computer2.png'
import profileHeader from '../assets/profileHeader.png'
import iconPerson from '../assets/iconPerson.svg'
import iconList from '../assets/iconList.svg'
import iconMedal from '../assets/iconMedal.svg'
import LandingPage from '../assets/LandingPage.png'
import MobileApp from '../assets/MobileApp.png'
import Branding from '../assets/Branding.png'
import serviceLandingPage from '../assets/serviceLandingPage.png'
import serviceMoble from '../assets/serviceMoble.png'
import serviceBranding from '../assets/serviceBranding.png'
import case1 from '../assets/case1.png'
import case2 from '../assets/case2.png'
import case3 from '../assets/case3.png'
import Portfolio1 from '../assets/Portfolio1.png'
import Portfolio2 from '../assets/Portfolio2.png'
import Portfolio3 from '../assets/Portfolio3.png'
import Portfolio4 from '../assets/Portfolio4.png'
import boxColor from '../assets/box-color.png'
import boxColor2 from '../assets/box-color2.png'
import quoteRight from '../assets/quote-right.svg'
import quoteLeft from '../assets/quote-left.svg'
import Ellipse2 from '../assets/Ellipse 2.png'


const linkImages = { logo, manComputer, manComputer2, profileHeader, iconPerson, iconList, iconMedal, LandingPage, MobileApp, Branding, serviceBranding, serviceLandingPage, serviceMoble, case1, case2, case3, Portfolio1, Portfolio2, Portfolio3, Portfolio4, boxColor, boxColor2, quoteLeft, quoteRight, Ellipse2 }

export default linkImages